[package]
name = 'bixverse_gpu'
publish = false
version = '0.2.5'
edition = '2021'
rust-version = '1.95'

[lib]
crate-type = ['staticlib', 'rlib']
name = 'bixverse_gpu'

[dependencies]
ann-search-rs = { version = "0.4.5", features = [ "gpu" ] }
burn = { version = "0.21.0", features = [ "wgpu", "flex" ] }
# TO UPDATE
bixverse-rs = { path = "/Users/gregorlueg/repos/shared/bixverse-rs", features = [ "gpu", "single-cell" ] }
cubecl = "0.10.0"
extendr-api = "0.9.0"
faer = { version = '0.23.2' }
rand_distr = "0.5.1"
[target.'cfg(not(windows))'.dependencies]
manifolds-rs = { path = "/Users/gregorlueg/repos/shared/manifold-rs", features = [ "fft_tsne", "gpu", "parametric" ] }
[target.'cfg(windows)'.dependencies]
manifolds-rs = { path = "/Users/gregorlueg/repos/shared/manifold-rs", features = [ "parametric", "gpu"] }


[profile.dev.package.faer]
opt-level = 3

[profile.test]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
strip = true

[[bin]]
name = "document"
path = "document.rs"
