# Generated by devforge. Do not edit.
# Edit the specs under inst/params/ and run devforge::forge_params().

# parameter checkers -----------------------------------------------------------

#' Check GPU k-means params
#'
#' @description Checkmate extension for the output of [params_kmeans_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkKMeansGpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "k_means_iter",
      "k_means_init",
      "metric",
      "fixed",
      "quantise"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      k_means_iter = "I1[1,)",
      k_means_init = c("S1", "0"),
      fixed = "B1",
      quantise = "B1"
    ),
    label = "GPU k-means params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      metric = c("euclidean", "cosine")
    ),
    label = "GPU k-means params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  if (
    !is.null(x[["k_means_init"]]) &&
      !checkmate::testChoice(
        x[["k_means_init"]],
        c("random", "parallel", "plusplus")
      )
  ) {
    return(paste(
      "Element `k_means_init` must be NULL or one of",
      "'random', 'parallel', or 'plusplus'."
    ))
  }

  return(TRUE)
}

#' Assert GPU k-means params
#'
#' @inheritParams checkKMeansGpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertKMeansGpuParams <- checkmate::makeAssertionFunction(checkKMeansGpuParams)

#' Check GPU nearest neighbour params
#'
#' @description Checkmate extension for the output of [params_nn_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkNnGpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "dist_metric",
      "n_list",
      "n_probes",
      "node_degree_final",
      "k_build",
      "n_tree",
      "delta",
      "rho",
      "beam_width",
      "max_beam_iters",
      "n_entry_points",
      "extract_knn"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      n_list = c("I1", "0"),
      n_probes = c("I1", "0"),
      node_degree_final = c("I1", "0"),
      k_build = c("I1", "0"),
      n_tree = c("I1", "0"),
      delta = "N1",
      rho = c("N1", "0"),
      beam_width = c("I1", "0"),
      max_beam_iters = c("I1", "0"),
      n_entry_points = c("I1", "0"),
      extract_knn = "B1"
    ),
    label = "GPU nearest neighbour params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      dist_metric = c("euclidean", "cosine")
    ),
    label = "GPU nearest neighbour params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert GPU nearest neighbour params
#'
#' @inheritParams checkNnGpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertNnGpuParams <- checkmate::makeAssertionFunction(checkNnGpuParams)

#' Check parametric UMAP params
#'
#' @description Checkmate extension for the output of
#' [params_parametric_umap()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkParametricUmapParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "local_connectivity",
      "bandwidth",
      "mix_weight",
      "hidden_layers",
      "lr",
      "corr_weight",
      "n_epochs",
      "batch_size",
      "neg_sample_rate"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      local_connectivity = "N1",
      bandwidth = "N1",
      mix_weight = "N1",
      hidden_layers = "X+[1,)",
      lr = "N1(0,)",
      corr_weight = "N1",
      n_epochs = "I1[1,)",
      batch_size = "I1[1,)",
      neg_sample_rate = "I1[1,)"
    ),
    label = "parametric UMAP params",
    hint = paste(
      "local_connectivity/bandwidth/mix_weight/corr_weight must be",
      "numeric, lr must be a positive numeric, hidden_layers must be a",
      "positive integer vector, and n_epochs/batch_size/neg_sample_rate",
      "must be positive integers."
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert parametric UMAP params
#'
#' @inheritParams checkParametricUmapParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertParametricUmapParams <- checkmate::makeAssertionFunction(
  checkParametricUmapParams
)

#' Check GPU fast clustering params
#'
#' @description Checkmate extension for the output of
#' [params_sc_fast_cluster_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkScFastClusterGpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "k_means_iter",
      "k_means_init",
      "fixed",
      "quantise",
      "same_weight",
      "full_snn",
      "pruning",
      "snn_similarity",
      "louvain_iters",
      "multi_level_louvain"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      k_means_iter = "I1[1,)",
      k_means_init = c("S1", "0"),
      fixed = "B1",
      quantise = "B1",
      same_weight = "B1",
      full_snn = "B1",
      pruning = c("N1[0,1]", "0"),
      louvain_iters = "I1[1,)",
      multi_level_louvain = "B1"
    ),
    label = "GPU fast clustering params",
    hint = paste(
      "See ?params_sc_fast_cluster_gpu and",
      "?bixverse::params_knn_defaults."
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      snn_similarity = c("jaccard", "rank")
    ),
    label = "GPU fast clustering params",
    hint = paste(
      "See ?params_sc_fast_cluster_gpu and",
      "?bixverse::params_knn_defaults."
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- check_list_shape(x, c("k", "knn_method", "ann_dist"))
  if (!isTRUE(res)) {
    return(res)
  }
  res <- apply_qtest_rules(
    x,
    list(
      k = "I1[1,)",
      n_trees = "I1[1,)",
      m = "I1[1,)",
      ef_construction = "I1[1,)",
      ef_search = "I1[1,)",
      search_budget = c("I1[1,)", "0"),
      ef_budget = c("I1[1,)", "0"),
      n_list = c("I1[1,)", "0"),
      n_probe = c("I1[1,)", "0"),
      delta = "N1[0,1]",
      diversify_prob = "N1[0,1]"
    ),
    label = "GPU fast clustering params"
  )
  if (!isTRUE(res)) {
    return(res)
  }
  if (
    !is.null(x[["k_means_init"]]) &&
      !checkmate::testChoice(
        x[["k_means_init"]],
        c("random", "parallel", "plusplus")
      )
  ) {
    return(paste(
      "Element `k_means_init` must be NULL or one of 'random',",
      "'parallel' or 'plusplus'."
    ))
  }
  res <- checkmate::checkChoice(x[["ann_dist"]], c("euclidean", "cosine"))
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert GPU fast clustering params
#'
#' @inheritParams checkScFastClusterGpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertScFastClusterGpuParams <- checkmate::makeAssertionFunction(
  checkScFastClusterGpuParams
)

#' Check Harmony v2 GPU params
#'
#' @description Checkmate extension for the output of
#' [params_sc_harmony_v2_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkScHarmonyV2GpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "k",
      "sigma",
      "theta",
      "lambda",
      "max_iter_kmeans",
      "max_iter_harmony",
      "epsilon_kmeans",
      "epsilon_harmony",
      "window_size",
      "alpha",
      "tau",
      "batch_proportion_cutoff",
      "use_dynamic_lambda",
      "csr_cube_count",
      "k_means_iter",
      "k_means_init",
      "fixed",
      "quantise"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      k = c("I1[1,)", "0"),
      sigma = "N+[0,)",
      theta = "N+[0,)",
      lambda = "N+[0,)",
      max_iter_kmeans = "I1[1,)",
      max_iter_harmony = "I1[1,)",
      epsilon_kmeans = "N1(0,)",
      epsilon_harmony = "N1(0,)",
      window_size = "I1[1,)",
      alpha = "N1(0,1)",
      tau = "N1[0,)",
      batch_proportion_cutoff = "N1(0,)",
      use_dynamic_lambda = "B1",
      csr_cube_count = "I1[1,)",
      k_means_iter = "I1[1,)",
      k_means_init = c("S1", "0"),
      fixed = "B1",
      quantise = "B1"
    ),
    label = "Harmony v2 GPU params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert Harmony v2 GPU params
#'
#' @inheritParams checkScHarmonyV2GpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertScHarmonyV2GpuParams <- checkmate::makeAssertionFunction(
  checkScHarmonyV2GpuParams
)

#' Check GPU t-SNE params
#'
#' @description Checkmate extension for the output of [params_tsne_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkTsneGpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "lr",
      "n_epochs",
      "early_exag_iter",
      "early_exag_factor",
      "late_exag_factor",
      "theta",
      "n_interp_points",
      "init",
      "randomised"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      lr = c("N1", "0"),
      n_epochs = "I1[1,)",
      early_exag_iter = "I1[1,)",
      early_exag_factor = "N1",
      late_exag_factor = c("N1", "0"),
      theta = "N1[0,1]",
      n_interp_points = "I1[1,)",
      randomised = "B1"
    ),
    label = "GPU t-SNE params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      init = c("pca", "spectral", "random")
    ),
    label = "GPU t-SNE params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert GPU t-SNE params
#'
#' @inheritParams checkTsneGpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertTsneGpuParams <- checkmate::makeAssertionFunction(checkTsneGpuParams)

#' Check GPU UMAP params
#'
#' @description Checkmate extension for the output of [params_umap_gpu()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkUmapGpuParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "local_connectivity",
      "bandwidth",
      "mix_weight",
      "lr",
      "n_epochs",
      "neg_sample_rate",
      "gamma",
      "optimiser",
      "init",
      "randomised"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      local_connectivity = "N1",
      bandwidth = "N1",
      mix_weight = "N1",
      lr = "N1",
      n_epochs = c("I1[1,)", "0"),
      neg_sample_rate = "I1",
      gamma = "N1",
      randomised = "B1"
    ),
    label = "GPU UMAP params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      optimiser = c("adam_gpu", "adam_parallel", "sgd", "adam"),
      init = c("spectral", "pca", "random")
    ),
    label = "GPU UMAP params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert GPU UMAP params
#'
#' @inheritParams checkUmapGpuParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertUmapGpuParams <- checkmate::makeAssertionFunction(checkUmapGpuParams)
