# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_bixverse_gpu_wrappers", use_symbols = TRUE, package_name = "bixverse.gpu")

#' @usage NULL
#' @useDynLib bixverse.gpu, .registration = TRUE
NULL

#' Generate a CAGRA kNN-based graph
#'
#' @export
rs_cagra_knn <- function(embd, cagra_params, extract_knn, seed, verbose) .Call(wrap__rs_cagra_knn, embd, cagra_params, extract_knn, seed, verbose)

#' Generate a CAGRA kNN-based graph
#'
#' @export
rs_ivf_gpu_knn <- function(embd, ivf_params, seed, verbose) .Call(wrap__rs_ivf_gpu_knn, embd, ivf_params, seed, verbose)


# nolint end
