# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_bixverse_gpu_wrappers", use_symbols = TRUE, package_name = "bixverse.gpu")

#' @usage NULL
#' @useDynLib bixverse.gpu, .registration = TRUE
NULL

#' Generate a CAGRA-style GPU-accelerated kNN graph
#'
#' Builds a kNN graph from an embedding matrix using the CAGRA algorithm on
#' the wgpu backend. Supports two retrieval modes: direct extraction from the
#' NNDescent graph, or beam search over the pruned CAGRA graph.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param cagra_params A named list with the parameters, see
#' [bixverse.gpu::params_sc_cagra()]
#' @param extract_knn Logical. If \code{TRUE}, extracts the kNN graph directly
#' from the NNDescent result (faster, slightly lower precision). If
#' \code{FALSE}, runs beam search over the pruned CAGRA graph (slower, higher
#' precision).
#' @param seed Integer. Random seed for reproducibility.
#' @param verbose Logical. Whether to print progress messages.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k_query with
#'  0-based neighbour indices.
#'  \item `dist` - Numeric matrix of shape cells x k_query with distances to
#'  the neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_cagra_gpu_knn <- function(embd, cagra_params, extract_knn, seed, verbose) .Call(wrap__rs_cagra_gpu_knn, embd, cagra_params, extract_knn, seed, verbose)

#' Generate an IVF-GPU-accelerated kNN graph
#'
#' Builds an IVF index over the provided embedding matrix and queries each
#' vector against it to produce a kNN graph. Runs on the wgpu backend.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param ivf_params A named list with the parameters, see
#' [bixverse.gpu::params_sc_ivf()]
#' @param seed Integer. Random seed for reproducibility.
#' @param verbose Logical. Whether to print progress messages.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k with 0-based neighbour
#'  indices.
#'  \item `dist` - Numeric matrix of shape cells x k with distances to the
#'  neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_ivf_gpu_knn <- function(embd, ivf_params, seed, verbose) .Call(wrap__rs_ivf_gpu_knn, embd, ivf_params, seed, verbose)

#' Generate an GPU-accelerated kNN graph from an exhaustive search
#'
#' Runs an exhaustive kNN search on the GPU.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param k Integer. Number of neighbours to return.
#' @param dist_metric String. Distance metric; one of
#' `c("euclidean", "cosine")`.
#' @param verbose Logical. Whether to print progress messages.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k with 0-based neighbour
#'  indices.
#'  \item `dist` - Numeric matrix of shape cells x k with distances to the
#'  neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_exhaustive_gpu_knn <- function(embd, k, dist_metric, verbose) .Call(wrap__rs_exhaustive_gpu_knn, embd, k, dist_metric, verbose)


# nolint end
