# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib bixverse.gpu, .registration = TRUE
NULL

#' Generate a CAGRA-style GPU-accelerated kNN graph
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Builds a kNN graph from an embedding matrix using the CAGRA algorithm on
#' the wgpu backend. Supports two retrieval modes: direct extraction from the
#' NNDescent graph, or beam search over the pruned CAGRA graph. The former
#' tends to have worse Recall.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param cagra_params A named list with the parameters, see
#' [bixverse.gpu::params_sc_cagra()]
#' @param extract_knn Logical. If \code{TRUE}, extracts the kNN graph directly
#' from the NNDescent result (faster, slightly lower precision). If
#' \code{FALSE}, runs beam search over the pruned CAGRA graph (slower, higher
#' precision).
#' @param seed Integer. Random seed for reproducibility.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k_query with
#'  0-based neighbour indices.
#'  \item `dist` - Numeric matrix of shape cells x k_query with distances to
#'  the neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_cagra_gpu_knn <- function(embd, cagra_params, extract_knn, seed, verbose) .Call(wrap__rs_cagra_gpu_knn, embd, cagra_params, extract_knn, seed, verbose)

#' Generate an IVF-GPU-accelerated kNN graph
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Builds an IVF index over the provided embedding matrix and queries each
#' vector against it to produce a kNN graph. Runs on the wgpu backend.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param ivf_params A named list with the parameters, see
#' [bixverse.gpu::params_sc_ivf()]
#' @param seed Integer. Random seed for reproducibility.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k with 0-based neighbour
#'  indices.
#'  \item `dist` - Numeric matrix of shape cells x k with distances to the
#'  neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_ivf_gpu_knn <- function(embd, ivf_params, seed, verbose) .Call(wrap__rs_ivf_gpu_knn, embd, ivf_params, seed, verbose)

#' Generate an GPU-accelerated kNN graph from an exhaustive search
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Runs an exhaustive kNN search on the GPU.
#'
#' @param embd Numeric matrix of embeddings, cells x features.
#' @param k Integer. Number of neighbours to return.
#' @param dist_metric String. Distance metric; one of
#' `c("euclidean", "cosine")`.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#'
#' @return A named list with:
#' \itemize{
#'  \item `indices` - Integer matrix of shape cells x k with 0-based neighbour
#'  indices.
#'  \item `dist` - Numeric matrix of shape cells x k with distances to the
#'  neighbours.
#'  \item `dist_metric` - Character. The distance metric used.
#' }
#'
#' @export
rs_exhaustive_gpu_knn <- function(embd, k, dist_metric, verbose) .Call(wrap__rs_exhaustive_gpu_knn, embd, k, dist_metric, verbose)

#' Parametric UMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Trains a neural network encoder to learn a mapping from the input space to a
#' low-dimensional embedding that preserves the UMAP graph structure. Supports
#' both GPU (wgpu) and CPU (burn flex CPU) backends. For small to medium data
#' sets (fewer than ~10k samples or narrow hidden layers), the CPU backend is
#' typically faster owing to GPU kernel dispatch overhead.
#'
#' @param data Numerical matrix. Data of dimensions samples x features.
#' @param n_dim Integer. Number of embedding dimensions.
#' @param k Integer. Number of nearest neighbours for graph construction.
#' @param min_dist Numeric. Minimum distance between embedded points.
#' @param spread Numeric. Effective scale of embedded points.
#' @param parametric_params Named list. Merged parametric UMAP parameters
#' containing nearest neighbour, graph, and training configuration.
#' @param seed Integer. Seed for reproducibility.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#' @param use_gpu Logical. If \code{TRUE}, trains on the wgpu backend. If
#' \code{FALSE}, trains on the CPU via NdArray. Defaults to \code{TRUE}.
#'
#' @return A named list with two elements: `embedding` (numerical matrix of
#' dimensions samples x n_dim) and `model` (external pointer to the trained
#' encoder for use with `rs_parametric_umap_predict`).
#'
#' @export
rs_parametric_umap <- function(data, n_dim, k, min_dist, spread, parametric_params, seed, verbose, use_gpu) .Call(wrap__rs_parametric_umap, data, n_dim, k, min_dist, spread, parametric_params, seed, verbose, use_gpu)

#' Predict new data using a trained parametric UMAP model
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Runs forward inference through the trained encoder network. The prediction
#' automatically uses whichever backend (GPU or CPU) the model was trained on.
#'
#' @param model External pointer to the trained parametric UMAP model, as
#' returned by `rs_parametric_umap`.
#' @param data Numerical matrix. New data of dimensions samples x features.
#' The number of features must match the training data.
#'
#' @return Numerical matrix of dimensions samples x n_dim with the predicted
#' embeddings.
#'
#' @export
rs_parametric_umap_predict <- function(model, data) .Call(wrap__rs_parametric_umap_predict, model, data)

#' Takes in a parametric UMAP and serialises it to raw bytes
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Serialises a trained parametric UMAP model to bytes for saving the data.
#'
#' @param model Robject. The trained parametric UMAP model to serialise.
#'
#' @returns The raw bytes of the model
#'
#' @keywords internal
rs_serialise_parametric_umap <- function(model) .Call(wrap__rs_serialise_parametric_umap, model)

#' Deserialises raw bytes to a trained UMAP model.
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Deserialises a trained parametric UMAP model from points and returns an R
#' object.
#'
#' @param bytes The raw byte sequence
#'
#' @returns Returns
#'
#' @keywords internal
rs_deserialise_parametric_umap <- function(bytes) .Call(wrap__rs_deserialise_parametric_umap, bytes)

#' GPU-accelerated k-means
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' A GPU-accelerated k-means version leveraging the wgpu backend via cubecl.
#'
#' @param data Numeric matrix. Samples x features.
#' @param dist String. Distance metric to use. One of
#' `c("euclidean", "cosine")`.
#' @param n_centroids Integer. Number of clusters, centroids to identify.
#' @param kmeans_params Named list. Contains specific parameters for the GPU-
#' accelerated k-means.
#' @param seed Integer. Seed for reproducibility.
#' @param verbose Boolean. Controls verbosity of the function.
#'
#' @returns A list with
#' \itemize{
#'   \item centoids - The centroids matrix (centroids x features)
#'   \item assignments - The cluster assignments of the data. (1-indexed.)
#' }
#'
#' @export
rs_kmeans_gpu <- function(data, dist, n_centroids, kmeans_params, seed, verbose) .Call(wrap__rs_kmeans_gpu, data, dist, n_centroids, kmeans_params, seed, verbose)

#' GPU-accelerated correlation calculations
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' GPU-accelerated pairwise column correlations. Has the options of Pearson and
#' Spearman correlation coefficient calculations.
#'
#' @param x Numerical matrix. The matrix for which to calculate the column
#' pairwise correlation matrix.
#' @param spearman Boolean. Shall the Spearman correlation be calculated
#' instead of Pearson.
#' @param verbose Boolean. Controls verbosity of the function.
#'
#' @returns The correlation matrix
#'
#' @export
rs_cor_gpu <- function(x, spearman, verbose) .Call(wrap__rs_cor_gpu, x, spearman, verbose)

#' GPU-accelerated covariance calculations
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' GPU-accelerated pairwise column co-variance calculation.
#'
#' @param x Numerical matrix. The matrix for which to calculate the column
#' pairwise covariance matrix.
#' @param verbose Boolean. Controls verbosity of the function.
#'
#' @returns The covariance matrix
#'
#' @export
rs_cov_gpu <- function(x, verbose) .Call(wrap__rs_cov_gpu, x, verbose)

#' UMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' This is the wrapper function into the Rust interface for GPU-accelerated
#' UMAP. Leverages GPU acceleration in the kNN search and also in the
#' optimisation.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of UMAP dimensions to return.
#' @param min_dist Numeric. Minimum distance to use.
#' @param spread Numeric. Spread parameter to use.
#' @param k Integer. Number of nearest neighbours to consider
#' @param umap_params Named list. List that contains all of the key parameters
#' for the UMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The UMAP embeddings.
#'
#' @export
rs_umap_gpu <- function(embd, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose) .Call(wrap__rs_umap_gpu, embd, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose)

#' UMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' This is the wrapper function into the Rust interface for UMAP and can use a
#' pre-computed kNN. Leverages GPU acceleration for the optimisation.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of UMAP dimensions to return.
#' @param min_dist Numeric. Minimum distance to use.
#' @param spread Numeric. Spread parameter to use.
#' @param k Integer. Number of nearest neighbours to consider
#' @param umap_params Named list. List that contains all of the key parameters
#' for the UMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The UMAP embeddings.
#'
#' @export
rs_umap_from_knn_gpu <- function(embd, knn_data, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose) .Call(wrap__rs_umap_from_knn_gpu, embd, knn_data, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose)

#' tSNE implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the tSNE implementation in manifolds-rs - a very fast Rust-based
#' implementation. You have two optimiser options: `"bh"` which tends to be
#' faster on smaller datasets and `"fft"` for large data sets. It leverages
#' GPU-accelerated kNN searches under the hood.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of tSNE dimensions to return. Needs to be two,
#' others are not supported.
#' @param perplexity Numeric. The tSNE perplexity parameter.
#' @param approx_type String. One of `c("fft", "bh")`. Which of the two
#' approximations to use.
#' @param tsne_params Named list. List that contains all of the key parameters
#' for the tSNE generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The tSNE embeddings.
#'
#' @export
rs_tsne_gpu <- function(embd, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose) .Call(wrap__rs_tsne_gpu, embd, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose)

#' tSNE implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the tSNE implementation in manifolds-rs - a very fast Rust-based
#' implementation. You have two optimiser options: `"bh"` which tends to be
#' faster on smaller datasets and `"fft"` for large data sets. This version
#' uses a pre-computed kNN graph, please see [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of tSNE dimensions to return. Needs to be two,
#' others are not supported.
#' @param perplexity Numeric. The tSNE perplexity parameter.
#' @param approx_type String. One of `c("fft", "bh")`. Which of the two
#' approximations to use.
#' @param tsne_params Named list. List that contains all of the key parameters
#' for the tSNE generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The tSNE embeddings.
#'
#' @export
rs_tsne_from_knn_gpu <- function(embd, knn_data, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose) .Call(wrap__rs_tsne_from_knn_gpu, embd, knn_data, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose)

#' Calculates sparse PCA for single cell
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Helper function that will calculate sparse PCA without scaling the data.
#' This has the advantage that you avoid creating a large dense matrix due
#' to scaling; however, it has the disadvantage that the first PC will be
#' heavily influenced by average expression. If random_svd is set to `FALSE`,
#' Lanczos iterations will be used to solve the SVD; if random_svd is set
#' to `TRUE`, the randomised version will be used with multiplication of the
#' initial sparse matrix with a much smaller random dense matrix, avoiding
#' holding a large dense matrix in memory.
#'
#' @param f_path_gene String. Path to the `counts_genes.bin` file.
#' @param f_path_cell String. Path to the `counts_cells.bin` file. Used if
#' you wish to use the PFlogPF transformation.
#' @param no_pcs Integer. Number of PCs to calculate.
#' @param pca_params Named list. Contains the parameters to use for this PCA
#' run. (Randomised will ignore, as gpu only supports randomised.)
#' @param cell_indices Integer. The cell indices to use. (0-indexed!)
#' @param gene_indices Integer. The gene indices to use. (0-indexed!)
#' @param seed Integer. Random seed for the randomised SVD.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#'
#' @returns A list with with the following items
#' \itemize{
#'   \item scores - The samples projected on the PCA space (solved via sparse
#'   SVD).
#'   \item loadings - The loadings of the features for the PCA (solved via
#'   sparse SVD).
#'   \item singular_values - The singular values for the PCA (solved via sparse
#'   SVD).
#' }
#'
#' @export
#'
#' @keywords internal
rs_sc_pca_sparse_gpu <- function(f_path_gene, f_path_cell, no_pcs, pca_params, cell_indices, gene_indices, seed, verbose) .Call(wrap__rs_sc_pca_sparse_gpu, f_path_gene, f_path_cell, no_pcs, pca_params, cell_indices, gene_indices, seed, verbose)

#' Harmony batch correction in Rust (version 2, GPU-accelerated)
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' This function implements the GPU-accelerated version 2 Harmony algorithm
#' from Patikas, et al., 2026. Only a single batch covariate is supported.
#'
#' @param pca Numerical matrix, i.e., the PCA matrix you want to correct.
#' @param harmony_params List. The parameters for the Harmony (v2) GPU algorithm.
#' @param batch_labels List. Must contain exactly one element: a 0-indexed
#' integer vector representing the batch effects you wish to regress out.
#' @param seed Integer. Seed for reproducibility purposes.
#' @param verbose Integer. `0L` - quiet; `1L` - normal verbosity; `2L` -
#' detailed verbosity.
#'
#' @return The batch-corrected Harmony (v2) embedding space.
#'
#' @export
rs_harmony_v2_gpu <- function(pca, harmony_params, batch_labels, seed, verbose) .Call(wrap__rs_harmony_v2_gpu, pca, harmony_params, batch_labels, seed, verbose)

#' GPU: SCENIC gene-regulatory network inference (disk-backed)
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' GPU equivalent of `bixverse::rs_scenic_grn`. Reads the target genes from
#' disk in chunks and dispatches per-batch tree fits to the WGPU backend.
#' GBM is not supported on GPU; use the CPU version.
#'
#' @param f_path_genes String. Path to the `counts_genes.bin` file.
#' @param cell_indices Integer vector. 0-indexed positions of cells to
#' include.
#' @param gene_indices Integer vector. 0-indexed positions of target genes.
#' @param tf_indices Integer vector. 0-indexed positions of TF predictors.
#' @param scenic_params Named list. See [bixverse::params_scenic()].
#' @param wave_byte_budget Double. VRAM ceiling for per-wave histogram +
#' cumulative tensors (bytes). Default 4 GiB.
#' @param seed Integer. Random seed.
#' @param verbose Integer. `0L` - quiet; `1L` - normal; `2L` - detailed.
#'
#' @returns A gene x TF importance matrix.
#'
#' @export
#'
#' @keywords internal
rs_scenic_grn_gpu <- function(f_path_genes, cell_indices, gene_indices, tf_indices, scenic_params, wave_byte_budget, seed, verbose) .Call(wrap__rs_scenic_grn_gpu, f_path_genes, cell_indices, gene_indices, tf_indices, scenic_params, wave_byte_budget, seed, verbose)

#' GPU: SCENIC GRN inference (streaming; bounded host memory)
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Streaming GPU equivalent of `bixverse::rs_scenic_grn_streaming`. Reads
#' targets in I/O chunks and dispatches each in-chunk batch serially to the
#' GPU. Peak host memory is bounded to one chunk of sparse columns.
#' GBM is not supported on GPU; use the CPU version.
#'
#' @param f_path_genes String. Path to the `counts_genes.bin` file.
#' @param cell_indices Integer vector. 0-indexed positions of cells to
#' include.
#' @param gene_indices Integer vector. 0-indexed positions of target genes.
#' @param tf_indices Integer vector. 0-indexed positions of TF predictors.
#' @param scenic_params Named list. See [bixverse::params_scenic()].
#' @param wave_byte_budget Double. VRAM ceiling for per-wave histogram +
#' cumulative tensors (bytes). Default 4 GiB.
#' @param seed Integer. Random seed.
#' @param verbose Integer. `0L` - quiet; `1L` - normal; `2L` - detailed.
#'
#' @returns A gene x TF importance matrix.
#'
#' @export
#'
#' @keywords internal
rs_scenic_grn_streaming_gpu <- function(f_path_genes, cell_indices, gene_indices, tf_indices, scenic_params, wave_byte_budget, seed, verbose) .Call(wrap__rs_scenic_grn_streaming_gpu, f_path_genes, cell_indices, gene_indices, tf_indices, scenic_params, wave_byte_budget, seed, verbose)

#' GPU: SCENIC GRN inference on MetaCells (in-memory sparse)
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' GPU equivalent of `bixverse::rs_mc_scenic`. Assumes the sparse data is
#' pre-filtered for the genes / cells to include. Indices are 0-indexed.
#' GBM is not supported on GPU; use the CPU version.
#'
#' @param sparse_data Named list with `data`, `indptr`, `indices`, `nrow`,
#' `ncol`, `format`.
#' @param tf_indices Integer vector. 0-indexed positions of TF predictors.
#' @param scenic_params Named list. See [bixverse::params_scenic()].
#' @param wave_byte_budget Double. VRAM ceiling for per-wave histogram +
#' cumulative tensors (bytes). Default 4 GiB.
#' @param seed Integer. Random seed.
#' @param verbose Integer. `0L` - quiet; `1L` - normal; `2L` - detailed.
#'
#' @returns A gene x TF importance matrix.
#'
#' @export
#'
#' @keywords internal
rs_mc_scenic_gpu <- function(sparse_data, tf_indices, scenic_params, wave_byte_budget, seed, verbose) .Call(wrap__rs_mc_scenic_gpu, sparse_data, tf_indices, scenic_params, wave_byte_budget, seed, verbose)

# nolint end
