# Generated by devforge. Do not edit.
# Edit the specs under inst/params/ and run devforge::forge_params().

# parameter wrappers -----------------------------------------------------------

#' Default parameters for GPU k-means
#'
#' @param k_means_iter Integer. Number of k-means iterations. Defaults to `50L`.
#' @param k_means_init String or `NULL`. Initialisation method. One of
#' `"random"`, `"parallel"`, or `"plusplus"`. If `NULL`, determined on the Rust
#' side. Defaults to `NULL`.
#' @param metric String. The distance metric. One of `c("euclidean", "cosine")`.
#' Defaults to `"euclidean"`.
#' @param fixed Boolean. Shall the algorithm be run for a fixed number of
#' iterations, without checking for convergence. Defaults to `FALSE`.
#' @param quantise Boolean. Whether to quantise data to `fp16` before
#' clustering. This can improve performance in circumstances where it is memory
#' bound. Defaults to `FALSE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item k_means_iter - Integer. Number of k-means iterations. Defaults to
#'  `50L`.
#'  \item k_means_init - String or `NULL`. Initialisation method. One of
#'  `"random"`, `"parallel"`, or `"plusplus"`. If `NULL`, determined on the Rust
#'  side. Defaults to `NULL`.
#'  \item metric - String. The distance metric. One of `c("euclidean",
#'  "cosine")`. Defaults to `"euclidean"`.
#'  \item fixed - Boolean. Shall the algorithm be run for a fixed number of
#'  iterations, without checking for convergence. Defaults to `FALSE`.
#'  \item quantise - Boolean. Whether to quantise data to `fp16` before
#'  clustering. This can improve performance in circumstances where it is memory
#'  bound. Defaults to `FALSE`.
#' }
#'
#' @export
params_kmeans_gpu <- function(
  k_means_iter = 50L,
  k_means_init = NULL,
  metric = c("euclidean", "cosine"),
  fixed = FALSE,
  quantise = FALSE
) {
  metric <- match.arg(metric)

  # Checks
  checkmate::qassert(k_means_iter, "I1[1,)")
  checkmate::qassert(k_means_init, c("S1", "0"))
  checkmate::assertChoice(metric, c("euclidean", "cosine"))
  checkmate::qassert(fixed, "B1")
  checkmate::qassert(quantise, "B1")

  if (!is.null(k_means_init)) {
    checkmate::assertChoice(k_means_init, c("random", "parallel", "plusplus"))
  }

  # Return
  list(
    k_means_iter = k_means_iter,
    k_means_init = k_means_init,
    metric = metric,
    fixed = fixed,
    quantise = quantise
  )
}

#' Default parameters for the GPU nearest neighbour backends
#'
#' @description GPU sibling of [bixverse::params_knn_defaults()]. The GPU
#' indices take a different knob set: there is no Annoy and no HNSW on the
#' device, so what survives is exhaustive, IVF and NN-descent.
#'
#' @details
#' NN-descent builds a CAGRA graph and, with `extract_knn = TRUE`, hands that
#' graph back rather than beam searching over it. Note that this saves the
#' query, not the build: the descent itself dominates, and its build degree
#' tracks `k`. NN-descent is therefore a low-`k` tool on the GPU. Above `k` of
#' roughly 30 both exhaustive and IVF beat it, and by `k = 200` they beat it by
#' more than an order of magnitude.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item k - Integer. Number of neighbours. `0L` hands the choice to Rust,
#'  which uses `sqrt(n_cells) * 0.5` and then adjusts for the simulated
#'  doublets. Defaults to `15L`.
#'  \item knn_method - String. The GPU index to use. One of `c("exhaustive",
#'  "ivf", "nndescent")`. Defaults to `"exhaustive"`.
#'  \item ann_dist - String. Manhattan is not supported by the GPU kernels. One
#'  of `c("euclidean", "cosine")`. Defaults to `"euclidean"`.
#'  \item n_list - Integer or `NULL`. IVF only. Number of clusters. `NULL` gives
#'  `sqrt(n)`. Defaults to `NULL`.
#'  \item n_probe - Integer or `NULL`. IVF only. Clusters to probe. `NULL` gives
#'  `sqrt(n_list)`. Defaults to `NULL`.
#'  \item graph_k - Integer or `NULL`. NN-descent only. Node degree of the graph
#'  after pruning. `NULL` gives 30, widened to cover `k` when `extract_knn` is
#'  set. Defaults to `NULL`.
#'  \item k_build - Integer or `NULL`. NN-descent only. Build degree before
#'  pruning. `NULL` gives `max(k, floor(1.5 * k))`. Defaults to `NULL`.
#'  \item n_tree - Integer or `NULL`. NN-descent only. Trees seeding the
#'  descent. Defaults to `NULL`.
#'  \item delta - Numeric. NN-descent only. Termination criterium for the
#'  descent. Defaults to `0.001`.
#'  \item rho - Numeric or `NULL`. NN-descent only. Sampling rate for the
#'  descent. Defaults to `NULL`.
#'  \item refine_knn - Integer or `NULL`. NN-descent only. 2-hop refinement
#'  sweeps after the descent. Buys graph quality at a linear cost. `NULL` gives
#'  0. Defaults to `NULL`.
#'  \item beam_width - Integer or `NULL`. NN-descent only. Beam width when
#'  querying. Ignored when `extract_knn` is set. Defaults to `NULL`.
#'  \item max_beam_iters - Integer or `NULL`. NN-descent only. Beam search
#'  iterations. Ignored when `extract_knn` is set. Defaults to `NULL`.
#'  \item n_entry_points - Integer or `NULL`. NN-descent only. Entry points when
#'  querying. Ignored when `extract_knn` is set. Defaults to `NULL`.
#'  \item extract_knn - Boolean. NN-descent only. Hand back the graph the
#'  descent built instead of beam searching over it. Defaults to `FALSE`.
#' }
#'
#' @export
params_knn_gpu_defaults <- function() {
  list(
    k = 15L,
    knn_method = "exhaustive",
    ann_dist = "euclidean",
    n_list = NULL,
    n_probe = NULL,
    graph_k = NULL,
    k_build = NULL,
    n_tree = NULL,
    delta = 0.001,
    rho = NULL,
    refine_knn = NULL,
    beam_width = NULL,
    max_beam_iters = NULL,
    n_entry_points = NULL,
    extract_knn = FALSE
  )
}

#' Wrapper function for parameters for GPU NEBULA
#'
#' @description GPU counterpart to [bixverse::params_nebula()]. Same knobs and
#' defaults, minus `reml`: the device fit does not implement it. Stage two of
#' NEBULA, the per-gene penalised fits, runs in `f32` on the device and is
#' finished on the host in `f64`, so the estimates sit close to the CPU ones
#' rather than on them.
#'
#' @param nebula_method String. Which variant to run. NEBULA downgrades `"ln"`
#' to `"hl"` below 30 cells per subject, as the R package does. One of `c("ln",
#' "hl")`. Defaults to `"ln"`.
#' @param min_sigma Numeric. Lower bound on the subject-level overdispersion.
#' Defaults to `1e-04`.
#' @param min_phi Numeric. Lower bound on the cell-level overdispersion.
#' Defaults to `1e-04`.
#' @param max_sigma Numeric. Upper bound on the subject-level overdispersion.
#' Defaults to `10.0`.
#' @param max_phi Numeric. Upper bound on the cell-level overdispersion.
#' Defaults to `1000.0`.
#' @param cutoff_cell Numeric. Refit both overdispersions when the product of
#' the cells per subject and the estimated `phi` falls below this. Defaults to
#' `20.0`.
#' @param kappa Numeric. Threshold on NEBULA's `kappa_obs` above which the
#' subject-level overdispersion from stage one is trusted as is. Defaults to
#' `800.0`.
#' @param cpc Numeric. Drop a gene whose mean count per cell is at most this.
#' Defaults to `0.005`.
#' @param mincp Integer. Drop a gene expressed in fewer than this many cells.
#' Defaults to `5L`.
#' @param eps Numeric. Absolute stopping tolerance for the optimiser. Defaults
#' to `1e-06`.
#' @param gene_batch_size Integer. Genes read and fitted per batch. Bounds how
#' much of the store is resident at once and changes nothing about the answer,
#' since NEBULA is gene-independent. Defaults to `1000L`.
#' @param shrink_dispersion Boolean. Shrink the cell-level overdispersions
#' towards an empirical Bayes prior once the sweep is done. Defaults to `TRUE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item nebula_method - String. Which variant to run. NEBULA downgrades `"ln"`
#'  to `"hl"` below 30 cells per subject, as the R package does. One of `c("ln",
#'  "hl")`. Defaults to `"ln"`.
#'  \item min_sigma - Numeric. Lower bound on the subject-level overdispersion.
#'  Defaults to `1e-04`.
#'  \item min_phi - Numeric. Lower bound on the cell-level overdispersion.
#'  Defaults to `1e-04`.
#'  \item max_sigma - Numeric. Upper bound on the subject-level overdispersion.
#'  Defaults to `10.0`.
#'  \item max_phi - Numeric. Upper bound on the cell-level overdispersion.
#'  Defaults to `1000.0`.
#'  \item cutoff_cell - Numeric. Refit both overdispersions when the product of
#'  the cells per subject and the estimated `phi` falls below this. Defaults to
#'  `20.0`.
#'  \item kappa - Numeric. Threshold on NEBULA's `kappa_obs` above which the
#'  subject-level overdispersion from stage one is trusted as is. Defaults to
#'  `800.0`.
#'  \item cpc - Numeric. Drop a gene whose mean count per cell is at most this.
#'  Defaults to `0.005`.
#'  \item mincp - Integer. Drop a gene expressed in fewer than this many cells.
#'  Defaults to `5L`.
#'  \item eps - Numeric. Absolute stopping tolerance for the optimiser. Defaults
#'  to `1e-06`.
#'  \item gene_batch_size - Integer. Genes read and fitted per batch. Bounds how
#'  much of the store is resident at once and changes nothing about the answer,
#'  since NEBULA is gene-independent. Defaults to `1000L`.
#'  \item shrink_dispersion - Boolean. Shrink the cell-level overdispersions
#'  towards an empirical Bayes prior once the sweep is done. Defaults to `TRUE`.
#' }
#'
#' @references He, et al., Commun Biol, 2021
#'
#' @export
params_nebula_gpu <- function(
  nebula_method = c("ln", "hl"),
  min_sigma = 1e-04,
  min_phi = 1e-04,
  max_sigma = 10.0,
  max_phi = 1000.0,
  cutoff_cell = 20.0,
  kappa = 800.0,
  cpc = 0.005,
  mincp = 5L,
  eps = 1e-06,
  gene_batch_size = 1000L,
  shrink_dispersion = TRUE
) {
  nebula_method <- match.arg(nebula_method)

  # Checks
  checkmate::assertChoice(nebula_method, c("ln", "hl"))
  checkmate::qassert(min_sigma, "N1(0,)")
  checkmate::qassert(min_phi, "N1(0,)")
  checkmate::qassert(max_sigma, "N1(0,)")
  checkmate::qassert(max_phi, "N1(0,)")
  checkmate::qassert(cutoff_cell, "N1[0,)")
  checkmate::qassert(kappa, "N1[0,)")
  checkmate::qassert(cpc, "N1[0,)")
  checkmate::qassert(mincp, "I1[0,)")
  checkmate::qassert(eps, "N1(0,)")
  checkmate::qassert(gene_batch_size, "I1[1,)")
  checkmate::qassert(shrink_dispersion, "B1")

  if (min_sigma >= max_sigma) {
    stop("`min_sigma` needs to be below `max_sigma`.")
  }
  if (min_phi >= max_phi) {
    stop("`min_phi` needs to be below `max_phi`.")
  }

  # Return
  list(
    nebula_method = nebula_method,
    min_sigma = min_sigma,
    min_phi = min_phi,
    max_sigma = max_sigma,
    max_phi = max_phi,
    cutoff_cell = cutoff_cell,
    kappa = kappa,
    cpc = cpc,
    mincp = mincp,
    eps = eps,
    gene_batch_size = gene_batch_size,
    shrink_dispersion = shrink_dispersion
  )
}

#' Wrapper function to generate GPU nearest neighbour parameters
#'
#' @param dist_metric String. The distance metric to use. One of `c("euclidean",
#' "cosine")`. Defaults to `"euclidean"`.
#' @param n_list Integer or `NULL`. IVF GPU: Number of clusters to use. If
#' `NULL`, will default to `sqrt(n)`. Defaults to `NULL`.
#' @param n_probes Integer or `NULL`. IVF GPU: Number of clusters to probe. If
#' `NULL`, will default to `sqrt(n_list)`. Defaults to `NULL`.
#' @param node_degree_final Integer or `NULL`. Final node degree of the CAGRA
#' navigational graph. If `NULL`, defaults to `30` on the Rust side. Defaults to
#' `NULL`.
#' @param k_build Integer or `NULL`. Number of k-neighbours during the NNDescent
#' build phase before CAGRA pruning. If `NULL`, defaults to `1.5 *
#' node_degree_final` on the Rust side. (Cannot be smaller than
#' `node_degree_final`) Defaults to `NULL`.
#' @param n_tree Integer or `NULL`. CAGRA GPU: Number of trees for graph build.
#' Automatically if `NULL`. Defaults to `NULL`.
#' @param delta Numeric. CAGRA GPU: Early termination parameter for NN descent.
#' Defaults to `0.001`.
#' @param rho Numeric or `NULL`. CAGRA GPU: Sample rate parameter for NN
#' descent. Defaults to `NULL`.
#' @param beam_width Integer or `NULL`. CAGRA GPU: Beam width for beam search.
#' If not provided will be set to `max(c(k, node_degree_final, 16L)) * 2`.
#' Defaults to `NULL`.
#' @param max_beam_iters Integer or `NULL`. CAGRA GPU: Maximum number of beam
#' search iterations. If not provided, defaults to `3 * beam_width`. Defaults to
#' `NULL`.
#' @param n_entry_points Integer or `NULL`. CAGRA GPU: Number of entry points
#' for beam search. If not provided, defaults to `8L`. Defaults to `NULL`.
#' @param extract_knn Boolean. CAGRA GPU: Skip the beam search and take the
#' graph the NNDescent left it. Faster, slightly lower recall. Ignored by the
#' other two searches. Defaults to `FALSE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item dist_metric - String. The distance metric to use. One of
#'  `c("euclidean", "cosine")`. Defaults to `"euclidean"`.
#'  \item n_list - Integer or `NULL`. IVF GPU: Number of clusters to use. If
#'  `NULL`, will default to `sqrt(n)`. Defaults to `NULL`.
#'  \item n_probes - Integer or `NULL`. IVF GPU: Number of clusters to probe. If
#'  `NULL`, will default to `sqrt(n_list)`. Defaults to `NULL`.
#'  \item node_degree_final - Integer or `NULL`. Final node degree of the CAGRA
#'  navigational graph. If `NULL`, defaults to `30` on the Rust side. Defaults
#'  to `NULL`.
#'  \item k_build - Integer or `NULL`. Number of k-neighbours during the
#'  NNDescent build phase before CAGRA pruning. If `NULL`, defaults to `1.5 *
#'  node_degree_final` on the Rust side. (Cannot be smaller than
#'  `node_degree_final`) Defaults to `NULL`.
#'  \item n_tree - Integer or `NULL`. CAGRA GPU: Number of trees for graph
#'  build. Automatically if `NULL`. Defaults to `NULL`.
#'  \item delta - Numeric. CAGRA GPU: Early termination parameter for NN
#'  descent. Defaults to `0.001`.
#'  \item rho - Numeric or `NULL`. CAGRA GPU: Sample rate parameter for NN
#'  descent. Defaults to `NULL`.
#'  \item beam_width - Integer or `NULL`. CAGRA GPU: Beam width for beam search.
#'  If not provided will be set to `max(c(k, node_degree_final, 16L)) * 2`.
#'  Defaults to `NULL`.
#'  \item max_beam_iters - Integer or `NULL`. CAGRA GPU: Maximum number of beam
#'  search iterations. If not provided, defaults to `3 * beam_width`. Defaults
#'  to `NULL`.
#'  \item n_entry_points - Integer or `NULL`. CAGRA GPU: Number of entry points
#'  for beam search. If not provided, defaults to `8L`. Defaults to `NULL`.
#'  \item extract_knn - Boolean. CAGRA GPU: Skip the beam search and take the
#'  graph the NNDescent left it. Faster, slightly lower recall. Ignored by the
#'  other two searches. Defaults to `FALSE`.
#' }
#'
#' @export
params_nn_gpu <- function(
  dist_metric = c("euclidean", "cosine"),
  n_list = NULL,
  n_probes = NULL,
  node_degree_final = NULL,
  k_build = NULL,
  n_tree = NULL,
  delta = 0.001,
  rho = NULL,
  beam_width = NULL,
  max_beam_iters = NULL,
  n_entry_points = NULL,
  extract_knn = FALSE
) {
  dist_metric <- match.arg(dist_metric)

  # Checks
  checkmate::assertChoice(dist_metric, c("euclidean", "cosine"))
  checkmate::qassert(n_list, c("I1", "0"))
  checkmate::qassert(n_probes, c("I1", "0"))
  checkmate::qassert(node_degree_final, c("I1", "0"))
  checkmate::qassert(k_build, c("I1", "0"))
  checkmate::qassert(n_tree, c("I1", "0"))
  checkmate::qassert(delta, "N1")
  checkmate::qassert(rho, c("N1", "0"))
  checkmate::qassert(beam_width, c("I1", "0"))
  checkmate::qassert(max_beam_iters, c("I1", "0"))
  checkmate::qassert(n_entry_points, c("I1", "0"))
  checkmate::qassert(extract_knn, "B1")

  # Return
  list(
    dist_metric = dist_metric,
    n_list = n_list,
    n_probes = n_probes,
    node_degree_final = node_degree_final,
    k_build = k_build,
    n_tree = n_tree,
    delta = delta,
    rho = rho,
    beam_width = beam_width,
    max_beam_iters = max_beam_iters,
    n_entry_points = n_entry_points,
    extract_knn = extract_knn
  )
}

#' Wrapper function to generate parametric UMAP parameters
#'
#' @param local_connectivity Numeric. Number of nearest neighbours assumed to be
#' at distance zero. Defaults to `1.0`.
#' @param bandwidth Numeric. Convergence tolerance for smooth kNN distance
#' binary search. Defaults to `1e-05`.
#' @param mix_weight Numeric. Balance between fuzzy union and directed graph
#' during symmetrisation. Defaults to `1.0`.
#' @param hidden_layers Integer vector. Hidden layer sizes for the MLP encoder.
#' Defaults to `c(128L, 64L, 32L)`.
#' @param lr Numeric. Learning rate for the neural network optimiser. Defaults
#' to `0.001`.
#' @param corr_weight Numeric. Coefficient for the negative Pearson correlation
#' loss that encourages similar distances in embedding and original space.
#' Defaults to `0.0`.
#' @param n_epochs Integer. Number of training epochs. Defaults to `500L`.
#' @param batch_size Integer. Training batch size. Defaults to `256L`.
#' @param neg_sample_rate Integer. Number of negative samples per positive edge.
#' Defaults to `5L`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item local_connectivity - Numeric. Number of nearest neighbours assumed to
#'  be at distance zero. Defaults to `1.0`.
#'  \item bandwidth - Numeric. Convergence tolerance for smooth kNN distance
#'  binary search. Defaults to `1e-05`.
#'  \item mix_weight - Numeric. Balance between fuzzy union and directed graph
#'  during symmetrisation. Defaults to `1.0`.
#'  \item hidden_layers - Integer vector. Hidden layer sizes for the MLP
#'  encoder. Defaults to `c(128L, 64L, 32L)`.
#'  \item lr - Numeric. Learning rate for the neural network optimiser. Defaults
#'  to `0.001`.
#'  \item corr_weight - Numeric. Coefficient for the negative Pearson
#'  correlation loss that encourages similar distances in embedding and original
#'  space. Defaults to `0.0`.
#'  \item n_epochs - Integer. Number of training epochs. Defaults to `500L`.
#'  \item batch_size - Integer. Training batch size. Defaults to `256L`.
#'  \item neg_sample_rate - Integer. Number of negative samples per positive
#'  edge. Defaults to `5L`.
#' }
#'
#' @export
params_parametric_umap <- function(
  local_connectivity = 1.0,
  bandwidth = 1e-05,
  mix_weight = 1.0,
  hidden_layers = c(128L, 64L, 32L),
  lr = 0.001,
  corr_weight = 0.0,
  n_epochs = 500L,
  batch_size = 256L,
  neg_sample_rate = 5L
) {
  # Checks
  checkmate::qassert(local_connectivity, "N1")
  checkmate::qassert(bandwidth, "N1")
  checkmate::qassert(mix_weight, "N1")
  checkmate::qassert(hidden_layers, "X+[1,)")
  checkmate::qassert(lr, "N1(0,)")
  checkmate::qassert(corr_weight, "N1")
  checkmate::qassert(n_epochs, "I1[1,)")
  checkmate::qassert(batch_size, "I1[1,)")
  checkmate::qassert(neg_sample_rate, "I1[1,)")

  hidden_layers <- as.integer(hidden_layers)

  # Return
  list(
    local_connectivity = local_connectivity,
    bandwidth = bandwidth,
    mix_weight = mix_weight,
    hidden_layers = hidden_layers,
    lr = lr,
    corr_weight = corr_weight,
    n_epochs = n_epochs,
    batch_size = batch_size,
    neg_sample_rate = neg_sample_rate
  )
}

#' Default parameters for GPU fast Louvain clustering
#'
#' @description GPU counterpart to [bixverse::params_sc_fast_cluster()]. The
#' mini-batch k-means knobs are gone (the GPU k-means is full-batch Lloyd's) and
#' the k-means block comes from the GPU parameters instead. Two knobs the CPU
#' wrapper never exposed, `same_weight` and `multi_level_louvain`, are available
#' here. The k-means distance is taken from `knn$ann_dist`, so the coarsening
#' and the centroid graph agree on the geometry. There is no separate `metric`
#' argument, and `"manhattan"` is not supported by the GPU k-means.
#'
#' @param k_means_iter Integer. Maximum number of k-means iterations. Defaults
#' to `50L`.
#' @param k_means_init String or `NULL`. Initialisation method. One of
#' `"random"`, `"parallel"` or `"plusplus"`. If `NULL`, picked on the Rust side
#' based on the number of centroids. Defaults to `NULL`.
#' @param fixed Boolean. Shall k-means run for a fixed number of iterations,
#' without checking for convergence. Defaults to `TRUE`.
#' @param quantise Boolean. Shall the data buffer be held at fp16 on the GPU.
#' Halves the buffer and helps when the assignment kernels are memory bound.
#' Defaults to `FALSE`.
#' @param same_weight Boolean. If `TRUE`, all kNN edges get weight `1.0`.
#' Otherwise edges with a reverse counterpart are double counted. Defaults to
#' `FALSE`.
#' @param full_snn Boolean. Shall the full shared nearest neighbour graph be
#' generated, including edges between centroids that are not neighbours.
#' Defaults to `FALSE`.
#' @param pruning Numeric or `NULL`. Weights below this threshold are set to 0
#' when generating the sNN graph. If `NULL`, defaults to `1 / ceiling(k * 0.8)`.
#' Defaults to `NULL`.
#' @param snn_similarity String. Jaccard computes the Jaccard index between
#' neighbour sets; rank weights edges by the best combined rank of a shared
#' neighbour. Both are normalised to `[0, 1]`. One of `c("jaccard", "rank")`.
#' Defaults to `"jaccard"`.
#' @param louvain_iters Integer. Number of Louvain iterations. Defaults to
#' `10L`.
#' @param multi_level_louvain Boolean. Shall multi-level Louvain be applied.
#' Defaults to `TRUE`.
#' @param knn List. Optional overrides for the kNN parameters applied to the
#' centroids. See [bixverse::params_knn_defaults()] for the available
#' parameters. Defaults to `list(k = 5L)`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item k_means_iter - Integer. Maximum number of k-means iterations. Defaults
#'  to `50L`.
#'  \item k_means_init - String or `NULL`. Initialisation method. One of
#'  `"random"`, `"parallel"` or `"plusplus"`. If `NULL`, picked on the Rust side
#'  based on the number of centroids. Defaults to `NULL`.
#'  \item fixed - Boolean. Shall k-means run for a fixed number of iterations,
#'  without checking for convergence. Defaults to `TRUE`.
#'  \item quantise - Boolean. Shall the data buffer be held at fp16 on the GPU.
#'  Halves the buffer and helps when the assignment kernels are memory bound.
#'  Defaults to `FALSE`.
#'  \item same_weight - Boolean. If `TRUE`, all kNN edges get weight `1.0`.
#'  Otherwise edges with a reverse counterpart are double counted. Defaults to
#'  `FALSE`.
#'  \item full_snn - Boolean. Shall the full shared nearest neighbour graph be
#'  generated, including edges between centroids that are not neighbours.
#'  Defaults to `FALSE`.
#'  \item pruning - Numeric or `NULL`. Weights below this threshold are set to 0
#'  when generating the sNN graph. If `NULL`, defaults to `1 / ceiling(k *
#'  0.8)`. Defaults to `NULL`.
#'  \item snn_similarity - String. Jaccard computes the Jaccard index between
#'  neighbour sets; rank weights edges by the best combined rank of a shared
#'  neighbour. Both are normalised to `[0, 1]`. One of `c("jaccard", "rank")`.
#'  Defaults to `"jaccard"`.
#'  \item louvain_iters - Integer. Number of Louvain iterations. Defaults to
#'  `10L`.
#'  \item multi_level_louvain - Boolean. Shall multi-level Louvain be applied.
#'  Defaults to `TRUE`.
#'  \item The elements of the base list, overridden by `knn`, spliced in at this
#'  position.
#' }
#'
#' @export
params_sc_fast_cluster_gpu <- function(
  k_means_iter = 50L,
  k_means_init = NULL,
  fixed = TRUE,
  quantise = FALSE,
  same_weight = FALSE,
  full_snn = FALSE,
  pruning = NULL,
  snn_similarity = c("jaccard", "rank"),
  louvain_iters = 10L,
  multi_level_louvain = TRUE,
  knn = list(k = 5L)
) {
  snn_similarity <- match.arg(snn_similarity)

  # Checks
  checkmate::qassert(k_means_iter, "I1[1,)")
  checkmate::qassert(k_means_init, c("S1", "0"))
  checkmate::qassert(fixed, "B1")
  checkmate::qassert(quantise, "B1")
  checkmate::qassert(same_weight, "B1")
  checkmate::qassert(full_snn, "B1")
  checkmate::qassert(pruning, c("N1[0,1]", "0"))
  checkmate::assertChoice(snn_similarity, c("jaccard", "rank"))
  checkmate::qassert(louvain_iters, "I1[1,)")
  checkmate::qassert(multi_level_louvain, "B1")

  # Merge
  knn <- utils::modifyList(
    bixverse::params_knn_defaults(),
    knn,
    keep.null = TRUE
  )

  if (!is.null(k_means_init)) {
    checkmate::assertChoice(k_means_init, c("random", "parallel", "plusplus"))
  }

  # Return
  c(
    list(
      k_means_iter = k_means_iter,
      k_means_init = k_means_init,
      fixed = fixed,
      quantise = quantise,
      same_weight = same_weight,
      full_snn = full_snn,
      pruning = pruning,
      snn_similarity = snn_similarity,
      louvain_iters = louvain_iters,
      multi_level_louvain = multi_level_louvain
    ),
    knn
  )
}

#' Default parameters for Harmony v2 GPU batch correction
#'
#' @param k Integer or `NULL`. Number of clusters for k-means clustering. If not
#' provided, it will be automatically determined as `min(round(N / 30), 100)`.
#' Defaults to `NULL`.
#' @param sigma Numeric vector. Per-cluster diversity weights. Either a single
#' value (broadcast to all clusters) or a vector of length k. Defaults to `0.1`.
#' @param theta Numeric vector. Per-variable diversity penalty. Must be a single
#' value; only one batch covariate is supported on the GPU path. Defaults to
#' `2.0`.
#' @param lambda Numeric vector. Ridge regression penalty for the linear model.
#' Typically a single value. Ignored when `use_dynamic_lambda = TRUE`. Defaults
#' to `1.0`.
#' @param max_iter_kmeans Integer. Maximum number of k-means Jacobi sweeps per
#' Harmony round. Defaults to `4L`.
#' @param max_iter_harmony Integer. Maximum number of Harmony outer iterations.
#' Defaults to `10L`.
#' @param epsilon_kmeans Numeric. Convergence threshold for k-means clustering.
#' Defaults to `0.001`.
#' @param epsilon_harmony Numeric. Convergence threshold for Harmony. Defaults
#' to `0.01`.
#' @param window_size Integer. Number of previous iterations to consider when
#' checking convergence. Defaults to `3L`.
#' @param alpha Numeric. Scaling factor for dynamic lambda estimation. Must be
#' in (0, 1). Only relevant when `use_dynamic_lambda = TRUE`. Defaults to `0.2`.
#' @param tau Numeric. Scaling factor for theta based on batch size. A value of
#' 0 disables batch-size scaling of theta. Defaults to `0.0`.
#' @param batch_proportion_cutoff Numeric. Cutoff for pruning batches with small
#' proportions during ridge regression. Defaults to `1e-05`.
#' @param use_dynamic_lambda Boolean. If `TRUE`, lambda is estimated dynamically
#' per cluster instead of using the fixed `lambda` value. Defaults to `FALSE`.
#' @param csr_cube_count Integer. Number of parallel thread groups used when
#' building the level-CSR index on the GPU. Adjust for your hardware if needed.
#' Defaults to `256L`.
#' @param k_means_iter Integer. Maximum number of k-means iterations for the
#' initial centroid computation. Defaults to `30L`.
#' @param k_means_init String or `NULL`. Initialisation strategy for k-means.
#' Defaults to `NULL`.
#' @param fixed Boolean. If `TRUE`, centroids are fixed after initialisation.
#' Defaults to `FALSE`.
#' @param quantise Boolean. If `TRUE`, quantises intermediate values to f16
#' during k-means. Defaults to `FALSE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item k - Integer or `NULL`. Number of clusters for k-means clustering. If
#'  not provided, it will be automatically determined as `min(round(N / 30),
#'  100)`. Defaults to `NULL`.
#'  \item sigma - Numeric vector. Per-cluster diversity weights. Either a single
#'  value (broadcast to all clusters) or a vector of length k. Defaults to
#'  `0.1`.
#'  \item theta - Numeric vector. Per-variable diversity penalty. Must be a
#'  single value; only one batch covariate is supported on the GPU path.
#'  Defaults to `2.0`.
#'  \item lambda - Numeric vector. Ridge regression penalty for the linear
#'  model. Typically a single value. Ignored when `use_dynamic_lambda = TRUE`.
#'  Defaults to `1.0`.
#'  \item max_iter_kmeans - Integer. Maximum number of k-means Jacobi sweeps per
#'  Harmony round. Defaults to `4L`.
#'  \item max_iter_harmony - Integer. Maximum number of Harmony outer
#'  iterations. Defaults to `10L`.
#'  \item epsilon_kmeans - Numeric. Convergence threshold for k-means
#'  clustering. Defaults to `0.001`.
#'  \item epsilon_harmony - Numeric. Convergence threshold for Harmony. Defaults
#'  to `0.01`.
#'  \item window_size - Integer. Number of previous iterations to consider when
#'  checking convergence. Defaults to `3L`.
#'  \item alpha - Numeric. Scaling factor for dynamic lambda estimation. Must be
#'  in (0, 1). Only relevant when `use_dynamic_lambda = TRUE`. Defaults to
#'  `0.2`.
#'  \item tau - Numeric. Scaling factor for theta based on batch size. A value
#'  of 0 disables batch-size scaling of theta. Defaults to `0.0`.
#'  \item batch_proportion_cutoff - Numeric. Cutoff for pruning batches with
#'  small proportions during ridge regression. Defaults to `1e-05`.
#'  \item use_dynamic_lambda - Boolean. If `TRUE`, lambda is estimated
#'  dynamically per cluster instead of using the fixed `lambda` value. Defaults
#'  to `FALSE`.
#'  \item csr_cube_count - Integer. Number of parallel thread groups used when
#'  building the level-CSR index on the GPU. Adjust for your hardware if needed.
#'  Defaults to `256L`.
#'  \item k_means_iter - Integer. Maximum number of k-means iterations for the
#'  initial centroid computation. Defaults to `30L`.
#'  \item k_means_init - String or `NULL`. Initialisation strategy for k-means.
#'  Defaults to `NULL`.
#'  \item fixed - Boolean. If `TRUE`, centroids are fixed after initialisation.
#'  Defaults to `FALSE`.
#'  \item quantise - Boolean. If `TRUE`, quantises intermediate values to f16
#'  during k-means. Defaults to `FALSE`.
#' }
#'
#' @export
params_sc_harmony_v2_gpu <- function(
  k = NULL,
  sigma = 0.1,
  theta = 2.0,
  lambda = 1.0,
  max_iter_kmeans = 4L,
  max_iter_harmony = 10L,
  epsilon_kmeans = 0.001,
  epsilon_harmony = 0.01,
  window_size = 3L,
  alpha = 0.2,
  tau = 0.0,
  batch_proportion_cutoff = 1e-05,
  use_dynamic_lambda = FALSE,
  csr_cube_count = 256L,
  k_means_iter = 30L,
  k_means_init = NULL,
  fixed = FALSE,
  quantise = FALSE
) {
  # Checks
  checkmate::qassert(k, c("I1[1,)", "0"))
  checkmate::qassert(sigma, "N+[0,)")
  checkmate::qassert(theta, "N+[0,)")
  checkmate::qassert(lambda, "N+[0,)")
  checkmate::qassert(max_iter_kmeans, "I1[1,)")
  checkmate::qassert(max_iter_harmony, "I1[1,)")
  checkmate::qassert(epsilon_kmeans, "N1(0,)")
  checkmate::qassert(epsilon_harmony, "N1(0,)")
  checkmate::qassert(window_size, "I1[1,)")
  checkmate::qassert(alpha, "N1(0,1)")
  checkmate::qassert(tau, "N1[0,)")
  checkmate::qassert(batch_proportion_cutoff, "N1(0,)")
  checkmate::qassert(use_dynamic_lambda, "B1")
  checkmate::qassert(csr_cube_count, "I1[1,)")
  checkmate::qassert(k_means_iter, "I1[1,)")
  checkmate::qassert(k_means_init, c("S1", "0"))
  checkmate::qassert(fixed, "B1")
  checkmate::qassert(quantise, "B1")

  # Return
  list(
    k = k,
    sigma = sigma,
    theta = theta,
    lambda = lambda,
    max_iter_kmeans = max_iter_kmeans,
    max_iter_harmony = max_iter_harmony,
    epsilon_kmeans = epsilon_kmeans,
    epsilon_harmony = epsilon_harmony,
    window_size = window_size,
    alpha = alpha,
    tau = tau,
    batch_proportion_cutoff = batch_proportion_cutoff,
    use_dynamic_lambda = use_dynamic_lambda,
    csr_cube_count = csr_cube_count,
    k_means_iter = k_means_iter,
    k_means_init = k_means_init,
    fixed = fixed,
    quantise = quantise
  )
}

#' Wrapper function to generate t-SNE parameters (GPU version)
#'
#' @param lr Numeric or `NULL`. Learning rate. If `NULL` (the default), the Rust
#' backend sets it to `max((n_samples / 12), 200)`, following the N-dependent
#' heuristic of Belkina et al. (2019). Defaults to `NULL`.
#' @param n_epochs Integer. Number of optimisation epochs. Defaults to `1000L`.
#' @param early_exag_iter Integer. Number of early exaggeration iterations.
#' Defaults to `250L`.
#' @param early_exag_factor Numeric. Early exaggeration factor. Defaults to
#' `12.0`.
#' @param late_exag_factor Numeric or `NULL`. If you wish to also use late
#' exaggerations. Can be useful on large data sets (set it to `2.0` to `4.0`).
#' Defaults to `NULL`.
#' @param theta Numeric. Barnes-Hut approximation angle. Lower values increase
#' accuracy at the cost of speed. Defaults to `0.5`.
#' @param n_interp_points Integer. Number of interpolation points per grid cell
#' for FFT acceleration. Defaults to `3L`.
#' @param init String. Embedding initialisation method. One of `c("pca",
#' "spectral", "random")`. Defaults to `"pca"`.
#' @param randomised Boolean. Use randomised SVD for PCA initialisation.
#' Defaults to `TRUE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item lr - Numeric or `NULL`. Learning rate. If `NULL` (the default), the
#'  Rust backend sets it to `max((n_samples / 12), 200)`, following the
#'  N-dependent heuristic of Belkina et al. (2019). Defaults to `NULL`.
#'  \item n_epochs - Integer. Number of optimisation epochs. Defaults to
#'  `1000L`.
#'  \item early_exag_iter - Integer. Number of early exaggeration iterations.
#'  Defaults to `250L`.
#'  \item early_exag_factor - Numeric. Early exaggeration factor. Defaults to
#'  `12.0`.
#'  \item late_exag_factor - Numeric or `NULL`. If you wish to also use late
#'  exaggerations. Can be useful on large data sets (set it to `2.0` to `4.0`).
#'  Defaults to `NULL`.
#'  \item theta - Numeric. Barnes-Hut approximation angle. Lower values increase
#'  accuracy at the cost of speed. Defaults to `0.5`.
#'  \item n_interp_points - Integer. Number of interpolation points per grid
#'  cell for FFT acceleration. Defaults to `3L`.
#'  \item init - String. Embedding initialisation method. One of `c("pca",
#'  "spectral", "random")`. Defaults to `"pca"`.
#'  \item randomised - Boolean. Use randomised SVD for PCA initialisation.
#'  Defaults to `TRUE`.
#' }
#'
#' @references Belkina, et al., Nat. Commun., 2019
#'
#' @export
params_tsne_gpu <- function(
  lr = NULL,
  n_epochs = 1000L,
  early_exag_iter = 250L,
  early_exag_factor = 12.0,
  late_exag_factor = NULL,
  theta = 0.5,
  n_interp_points = 3L,
  init = c("pca", "spectral", "random"),
  randomised = TRUE
) {
  init <- match.arg(init)

  # Checks
  checkmate::qassert(lr, c("N1", "0"))
  checkmate::qassert(n_epochs, "I1[1,)")
  checkmate::qassert(early_exag_iter, "I1[1,)")
  checkmate::qassert(early_exag_factor, "N1")
  checkmate::qassert(late_exag_factor, c("N1", "0"))
  checkmate::qassert(theta, "N1[0,1]")
  checkmate::qassert(n_interp_points, "I1[1,)")
  checkmate::assertChoice(init, c("pca", "spectral", "random"))
  checkmate::qassert(randomised, "B1")

  # Return
  list(
    lr = lr,
    n_epochs = n_epochs,
    early_exag_iter = early_exag_iter,
    early_exag_factor = early_exag_factor,
    late_exag_factor = late_exag_factor,
    theta = theta,
    n_interp_points = n_interp_points,
    init = init,
    randomised = randomised
  )
}

#' Wrapper function to generate UMAP parameters (GPU version)
#'
#' @param local_connectivity Numeric. Number of nearest neighbours assumed to be
#' at distance zero. Defaults to `1.0`.
#' @param bandwidth Numeric. Convergence tolerance for smooth kNN distance
#' binary search. Defaults to `1e-05`.
#' @param mix_weight Numeric. Balance between fuzzy union and directed graph
#' during symmetrisation. Defaults to `1.0`.
#' @param lr Numeric. Learning rate. Defaults to `1.0`.
#' @param n_epochs Integer or `NULL`. Number of optimisation epochs. Defaults to
#' `NULL`.
#' @param neg_sample_rate Integer. Number of negative samples per positive
#' sample. Defaults to `5L`.
#' @param gamma Numeric. Repulsion strength. Defaults to `1.0`.
#' @param optimiser String. The optimiser for the embedding. One of
#' `c("adam_gpu", "adam_parallel", "sgd", "adam")`. Defaults to `"adam_gpu"`.
#' @param init String. Embedding initialisation method. One of `c("spectral",
#' "pca", "random")`. Defaults to `"spectral"`.
#' @param randomised Boolean. Use randomised SVD for PCA initialisation.
#' Defaults to `FALSE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item local_connectivity - Numeric. Number of nearest neighbours assumed to
#'  be at distance zero. Defaults to `1.0`.
#'  \item bandwidth - Numeric. Convergence tolerance for smooth kNN distance
#'  binary search. Defaults to `1e-05`.
#'  \item mix_weight - Numeric. Balance between fuzzy union and directed graph
#'  during symmetrisation. Defaults to `1.0`.
#'  \item lr - Numeric. Learning rate. Defaults to `1.0`.
#'  \item n_epochs - Integer or `NULL`. Number of optimisation epochs. Defaults
#'  to `NULL`.
#'  \item neg_sample_rate - Integer. Number of negative samples per positive
#'  sample. Defaults to `5L`.
#'  \item gamma - Numeric. Repulsion strength. Defaults to `1.0`.
#'  \item optimiser - String. The optimiser for the embedding. One of
#'  `c("adam_gpu", "adam_parallel", "sgd", "adam")`. Defaults to `"adam_gpu"`.
#'  \item init - String. Embedding initialisation method. One of `c("spectral",
#'  "pca", "random")`. Defaults to `"spectral"`.
#'  \item randomised - Boolean. Use randomised SVD for PCA initialisation.
#'  Defaults to `FALSE`.
#' }
#'
#' @export
params_umap_gpu <- function(
  local_connectivity = 1.0,
  bandwidth = 1e-05,
  mix_weight = 1.0,
  lr = 1.0,
  n_epochs = NULL,
  neg_sample_rate = 5L,
  gamma = 1.0,
  optimiser = c("adam_gpu", "adam_parallel", "sgd", "adam"),
  init = c("spectral", "pca", "random"),
  randomised = FALSE
) {
  optimiser <- match.arg(optimiser)
  init <- match.arg(init)

  # Checks
  checkmate::qassert(local_connectivity, "N1")
  checkmate::qassert(bandwidth, "N1")
  checkmate::qassert(mix_weight, "N1")
  checkmate::qassert(lr, "N1")
  checkmate::qassert(n_epochs, c("I1[1,)", "0"))
  checkmate::qassert(neg_sample_rate, "I1")
  checkmate::qassert(gamma, "N1")
  checkmate::assertChoice(
    optimiser,
    c("adam_gpu", "adam_parallel", "sgd", "adam")
  )
  checkmate::assertChoice(init, c("spectral", "pca", "random"))
  checkmate::qassert(randomised, "B1")

  # Return
  list(
    local_connectivity = local_connectivity,
    bandwidth = bandwidth,
    mix_weight = mix_weight,
    lr = lr,
    n_epochs = n_epochs,
    neg_sample_rate = neg_sample_rate,
    gamma = gamma,
    optimiser = optimiser,
    init = init,
    randomised = randomised
  )
}
