# ------------------------------------------------------------------------------
# GPU-accelerated SEACells:
# - Wraps `rs_seacells_gpu`.
# - Reuses bixverse's `params_sc_seacells()` and returns the same `MetaCells`
#   object as the CPU `generate_seacells_sc()`.
# - bixverse dispatches on its internal `ScOrScSubset` union. That union is not
#   exported, so the two exported classes get a method each and both delegate to
#   `.generate_seacells_gpu()`.
# ------------------------------------------------------------------------------

# seacells (gpu) ---------------------------------------------------------------

#' Generate meta cells based on SEACells on the GPU
#'
#' @description
#' GPU counterpart of [bixverse::generate_seacells_sc()]. Both Frank-Wolfe
#' solves, the B-gradient argmin and the per-cell A columns, run on the WGPU
#' backend. Kernel construction, archetype initialisation, the `K^2 B`
#' bookkeeping, the RSS evaluation and the aggregation into pseudo-bulk counts
#' stay on the CPU, so the speedup tracks how much of the run the two solves
#' own. That share grows with `n_sea_cells`. Each solve falls back to its CPU
#' sibling for that iteration if no GPU workgroup tier covers `k`.
#'
#' Params, result class and downstream code are identical to the CPU version.
#'
#' @param object `SingleCells` or `SingleCellsSubset` class from `bixverse`.
#' @param seacell_params List. Output of [bixverse::params_sc_seacells()].
#' A list with the following items:
#' \itemize{
#'   \item n_sea_cells - Number of SEA cells to detect.
#'   \item max_fw_iters - Maximum iterations for the Frank-Wolfe algorithm per
#'   matrix update.
#'   \item convergence_epsilon - Convergence threshold. Algorithm stops when
#'   RSS change < epsilon * RSS(0).
#'   \item max_iter - Maximum iterations to run SEACells for.
#'   \item min_iter - Minimum iterations to run SEACells for.
#'   \item greedy_threshold - Maximum number of cells before defaulting to rapid
#'   random selection of archetypes.
#'   \item graph_building - Graph building method.
#'   \item pruning - Boolean. Shall small values be pruned during the Frank-
#'   Wolfe iterations.
#'   \item pruning_threshold - The threshold below which pruning shall be
#'   applied during Frank-Wolfe iterations.
#'   \item n_landmarks - Optional integer. Number of landmarks for the Nystroem
#'   archetype initialisation.
#'   \item knn - List of kNN parameters. See [bixverse::params_knn_defaults()]
#'   for available parameters and their defaults.
#' }
#' @param embd_to_use String. The embedding to use. Atm, the only option is
#' `"pca"`.
#' @param no_embd_to_use Optional integer. Number of embedding dimensions to
#' use. If `NULL` all will be used.
#' @param cells_to_use Optional string. Names of the cells to use for the
#' generation of the SEACells. Forces a kNN rebuild on that subset.
#' @param regenerate_knn Boolean. Shall a kNN graph be regenerated. If not,
#' the internal one will be used.
#' @param target_size Numeric. The library target size to normalise the meta
#' cells to.
#' @param seed Integer. Seed for reproducibility.
#' @param .verbose Boolean or integer. Controls verbosity and returns run times.
#' `FALSE` -> quiet, `TRUE` or `1L` -> normal verbosity, `2L` -> detailed
#' verbosity.
#'
#' @returns A [bixverse::MetaCells()] with the data generated by this meta cell
#' aggregation method.
#'
#' @export
#'
#' @references
#' Persad, et al. Nat Biotechnol, 2023
generate_seacells_gpu_sc <- S7::new_generic(
  name = "generate_seacells_gpu_sc",
  dispatch_args = "object",
  fun = function(
    object,
    seacell_params = bixverse::params_sc_seacells(),
    embd_to_use = "pca",
    no_embd_to_use = NULL,
    cells_to_use = NULL,
    regenerate_knn = FALSE,
    target_size = 1e5,
    seed = 42L,
    .verbose = TRUE
  ) {
    S7::S7_dispatch()
  }
)

## SingleCells -----------------------------------------------------------------

#' @method generate_seacells_gpu_sc SingleCells
#'
#' @export
#'
#' @import bixverse
S7::method(generate_seacells_gpu_sc, SingleCells) <- function(
  object,
  seacell_params = bixverse::params_sc_seacells(),
  embd_to_use = "pca",
  no_embd_to_use = NULL,
  cells_to_use = NULL,
  regenerate_knn = FALSE,
  target_size = 1e5,
  seed = 42L,
  .verbose = TRUE
) {
  .generate_seacells_gpu(
    object = object,
    seacell_params = seacell_params,
    embd_to_use = embd_to_use,
    no_embd_to_use = no_embd_to_use,
    cells_to_use = cells_to_use,
    regenerate_knn = regenerate_knn,
    target_size = target_size,
    seed = seed,
    .verbose = .verbose
  )
}

## SingleCellsSubset -----------------------------------------------------------

#' @method generate_seacells_gpu_sc SingleCellsSubset
#'
#' @export
#'
#' @import bixverse
S7::method(generate_seacells_gpu_sc, SingleCellsSubset) <- function(
  object,
  seacell_params = bixverse::params_sc_seacells(),
  embd_to_use = "pca",
  no_embd_to_use = NULL,
  cells_to_use = NULL,
  regenerate_knn = FALSE,
  target_size = 1e5,
  seed = 42L,
  .verbose = TRUE
) {
  .generate_seacells_gpu(
    object = object,
    seacell_params = seacell_params,
    embd_to_use = embd_to_use,
    no_embd_to_use = no_embd_to_use,
    cells_to_use = cells_to_use,
    regenerate_knn = regenerate_knn,
    target_size = target_size,
    seed = seed,
    .verbose = .verbose
  )
}

## implementation --------------------------------------------------------------

#' Shared implementation of the GPU SEACells generation
#'
#' @description
#' Body behind both `generate_seacells_gpu_sc()` methods. Pulls the embedding
#' and the cached kNN graph off the object, hands them to [rs_seacells_gpu()]
#' and wraps the result into a [bixverse::MetaCells()].
#'
#' @inheritParams generate_seacells_gpu_sc
#'
#' @returns A [bixverse::MetaCells()].
#'
#' @keywords internal
.generate_seacells_gpu <- function(
  object,
  seacell_params,
  embd_to_use,
  no_embd_to_use,
  cells_to_use,
  regenerate_knn,
  target_size,
  seed,
  .verbose
) {
  # checks
  checkmate::assertTRUE(
    S7::S7_inherits(object, bixverse::SingleCells) ||
      S7::S7_inherits(object, bixverse::SingleCellsSubset)
  )
  bixverse:::assertScSeacells(seacell_params)
  checkmate::qassert(embd_to_use, "S1")
  checkmate::qassert(no_embd_to_use, c("I1", "0"))
  checkmate::qassert(cells_to_use, c("S+", "0"))
  checkmate::qassert(regenerate_knn, "B1")
  checkmate::qassert(target_size, "N1")
  checkmate::qassert(seed, "I1")
  checkmate::qassert(.verbose, c("B1", "I1[0,2]"))

  # hard tier: cell indices from here go straight into Rust
  bixverse::assert_sc_state(
    object,
    artefacts = c(embd_to_use, if (!regenerate_knn) "knn")
  )

  # function body
  embd <- bixverse::get_embedding(x = object, embd_name = embd_to_use)

  if (!is.null(no_embd_to_use)) {
    to_take <- min(c(no_embd_to_use, ncol(embd)))
    embd <- embd[, 1:to_take]
  }

  if (!is.null(cells_to_use)) {
    cells_to_use <- bixverse::get_cell_indices(
      object,
      cell_ids = cells_to_use,
      rust_index = TRUE
    )
  }

  knn_data <- if (regenerate_knn) {
    NULL
  } else {
    bixverse::get_knn_obj(object)
  }

  seacell_data <- rs_seacells_gpu(
    f_path = bixverse:::get_rust_count_cell_f_path(object),
    embd = embd,
    cells_to_use = cells_to_use,
    cells_to_keep = bixverse::get_cells_to_keep(object),
    knn_data = knn_data,
    seacells_params = seacell_params,
    target_size = target_size,
    seed = seed,
    verbose = bixverse:::parse_verbosity(.verbose)
  )

  var_data <- bixverse::get_sc_var(object, cols = c("gene_idx", "gene_id"))

  bixverse::MetaCells(
    meta_cell_data = seacell_data,
    var_data = var_data,
    meta_cell_method = "seacell"
  )
}
